In [ ]:
import pandas as pd 
import sweetviz
import numpy as np

In [ ]:
import matplotlib as plt
%matplotlib inline

In [ ]:
hospital = pd.read_csv('https://raw.githubusercontent.com/hantswilliams/AHI_DataSci_507/main/Deployment_Streamlit/hospital_info.csv')
hospital

     provider_id  ...                              location
0         310119  ...            POINT (-74.19213 40.74095)
1         310016  ...  POINT (-74.05014200000001 40.734876)
2         390123  ...          POINT (-75.611502 40.243941)
3         440002  ...           POINT (-88.831973 35.63954)
4         330080  ...          POINT (-73.924072 40.817681)
...          ...  ...                                   ...
5309      49001F  ...          POINT (-77.142608 38.705877)
5310      26002F  ...          POINT (-92.116491 37.766471)
5311      50014F  ...         POINT (-122.680142 48.336875)
5312      21007F  ...           POINT (-77.096801 38.99949)
5313      45070F  ...          POINT (-97.775132 31.130337)

[5314 rows x 29 columns]

In [ ]:
outpatient = pd.read_csv('https://raw.githubusercontent.com/hantswilliams/AHI_DataSci_507/main/Deployment_Streamlit/outpatient_2015.csv')
outpatient.sample(5)

       provider_id  ... average_total_payments
5475        380014  ...             572.318000
25374        40134  ...             369.631739
17195       140294  ...             209.549667
7892        160117  ...              87.733333
1867        390043  ...              86.515414

[5 rows x 11 columns]

In [ ]:
inpatient = pd.read_csv('https://raw.githubusercontent.com/hantswilliams/AHI_DataSci_507/main/Deployment_Streamlit/inpatient_2015.csv')
inpatient.sample(5)

        provider_id  ... average_medicare_payments
55393        230041  ...                   8497.47
122649       490113  ...                   3972.93
84531        380001  ...                   7191.42
184962       440063  ...                   4751.15
152958       510022  ...                   3642.00

[5 rows x 12 columns]

#Check the Length of each database

```
# This is formatted as code
```

In [ ]:
print ('hospital Length:' , len(hospital))
print ('Inpatient Length:' , len(inpatient))
print ('Outpatient Length:' , len(outpatient))

hospital Length: 5314
Inpatient Length: 201876
Outpatient Length: 32532

# List all colunms/variables in the database

In [ ]:
list(hospital)

['provider_id',
 'hospital_name',
 'address',
 'city',
 'state',
 'zip_code',
 'county_name',
 'phone_number',
 'hospital_type',
 'hospital_ownership',
 'emergency_services',
 'meets_criteria_for_meaningful_use_of_ehrs',
 'hospital_overall_rating',
 'hospital_overall_rating_footnote',
 'mortality_national_comparison',
 'mortality_national_comparison_footnote',
 'safety_of_care_national_comparison',
 'safety_of_care_national_comparison_footnote',
 'readmission_national_comparison',
 'readmission_national_comparison_footnote',
 'patient_experience_national_comparison',
 'patient_experience_national_comparison_footnote',
 'effectiveness_of_care_national_comparison',
 'effectiveness_of_care_national_comparison_footnote',
 'timeliness_of_care_national_comparison',
 'timeliness_of_care_national_comparison_footnote',
 'efficient_use_of_medical_imaging_national_comparison',
 'efficient_use_of_medical_imaging_national_comparison_footnote',
 'location']

In [ ]:
list(inpatient)

['provider_id',
 'provider_name',
 'provider_street_address',
 'provider_city',
 'provider_state',
 'provider_zipcode',
 'drg_definition',
 'hospital_referral_region_description',
 'total_discharges',
 'average_covered_charges',
 'average_total_payments',
 'average_medicare_payments']

In [ ]:
list(outpatient)

['provider_id',
 'provider_name',
 'provider_street_address',
 'provider_city',
 'provider_state',
 'provider_zipcode',
 'apc',
 'hospital_referral_region',
 'outpatient_services',
 'average_estimated_submitted_charges',
 'average_total_payments']

#Looks at Pandas ProfileReport for each dataset

In [ ]:
!pip install -U https://github.com/pandas-profiling/pandas-profiling/archive/master.zip

!pip install -U pandas-profiling

import pandas_profiling as pp
from pandas_profiling import ProfileReport

Collecting https://github.com/pandas-profiling/pandas-profiling/archive/master.zip
  Using cached https://github.com/pandas-profiling/pandas-profiling/archive/master.zip
Requirement already satisfied: joblib~=1.1.0 in /usr/local/lib/python3.7/dist-packages (from pandas-profiling==3.1.1) (1.1.0)
Requirement already satisfied: scipy>=1.4.1 in /usr/local/lib/python3.7/dist-packages (from pandas-profiling==3.1.1) (1.7.3)
Requirement already satisfied: pandas!=1.0.0,!=1.0.1,!=1.0.2,!=1.1.0,>=0.25.3 in /usr/local/lib/python3.7/dist-packages (from pandas-profiling==3.1.1) (1.1.5)
Requirement already satisfied: matplotlib>=3.2.0 in /usr/local/lib/python3.7/dist-packages (from pandas-profiling==3.1.1) (3.2.2)
Requirement already satisfied: pydantic>=1.8.1 in /usr/local/lib/python3.7/dist-packages (from pandas-profiling==3.1.1) (1.8.2)
Requirement already satisfied: PyYAML>=5.0.0 in /usr/local/lib/python3.7/dist-packages (from pandas-profiling==3.1.1) (6.0)
Requirement already satisfied: jinja2>=2.11.1 in /usr/local/lib/python3.7/dist-packages (from pandas-profiling==3.1.1) (2.11.3)
Requirement already satisfied: markupsafe~=2.0.1 in /usr/local/lib/python3.7/dist-packages (from pandas-profiling==3.1.1) (2.0.1)
Requirement already satisfied: visions[type_image_path]==0.7.4 in /usr/local/lib/python3.7/dist-packages (from pandas-profiling==3.1.1) (0.7.4)
Requirement already satisfied: numpy>=1.16.0 in /usr/local/lib/python3.7/dist-packages (from pandas-profiling==3.1.1) (1.19.5)
Requirement already satisfied: htmlmin>=0.1.12 in /usr/local/lib/python3.7/dist-packages (from pandas-profiling==3.1.1) (0.1.12)
Requirement already satisfied: missingno>=0.4.2 in /usr/local/lib/python3.7/dist-packages (from pandas-profiling==3.1.1) (0.5.0)
Requirement already satisfied: phik>=0.11.1 in /usr/local/lib/python3.7/dist-packages (from pandas-profiling==3.1.1) (0.12.0)
Requirement already satisfied: tangled-up-in-unicode==0.2.0 in /usr/local/lib/python3.7/dist-packages (from pandas-profiling==3.1.1) (0.2.0)
Requirement already satisfied: requests>=2.24.0 in /usr/local/lib/python3.7/dist-packages (from pandas-profiling==3.1.1) (2.26.0)
Requirement already satisfied: tqdm>=4.48.2 in /usr/local/lib/python3.7/dist-packages (from pandas-profiling==3.1.1) (4.62.3)
Requirement already satisfied: seaborn>=0.10.1 in /usr/local/lib/python3.7/dist-packages (from pandas-profiling==3.1.1) (0.11.2)
Requirement already satisfied: multimethod>=1.4 in /usr/local/lib/python3.7/dist-packages (from pandas-profiling==3.1.1) (1.6)
Requirement already satisfied: networkx>=2.4 in /usr/local/lib/python3.7/dist-packages (from visions[type_image_path]==0.7.4->pandas-profiling==3.1.1) (2.6.3)
Requirement already satisfied: attrs>=19.3.0 in /usr/local/lib/python3.7/dist-packages (from visions[type_image_path]==0.7.4->pandas-profiling==3.1.1) (21.2.0)
Requirement already satisfied: Pillow in /usr/local/lib/python3.7/dist-packages (from visions[type_image_path]==0.7.4->pandas-profiling==3.1.1) (7.1.2)
Requirement already satisfied: imagehash in /usr/local/lib/python3.7/dist-packages (from visions[type_image_path]==0.7.4->pandas-profiling==3.1.1) (4.2.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=3.2.0->pandas-profiling==3.1.1) (1.3.2)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=3.2.0->pandas-profiling==3.1.1) (3.0.6)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=3.2.0->pandas-profiling==3.1.1) (0.11.0)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=3.2.0->pandas-profiling==3.1.1) (2.8.2)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.7/dist-packages (from pandas!=1.0.0,!=1.0.1,!=1.0.2,!=1.1.0,>=0.25.3->pandas-profiling==3.1.1) (2018.9)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.7/dist-packages (from pydantic>=1.8.1->pandas-profiling==3.1.1) (3.10.0.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.1->matplotlib>=3.2.0->pandas-profiling==3.1.1) (1.15.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests>=2.24.0->pandas-profiling==3.1.1) (2.10)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.7/dist-packages (from requests>=2.24.0->pandas-profiling==3.1.1) (2.0.8)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests>=2.24.0->pandas-profiling==3.1.1) (1.24.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests>=2.24.0->pandas-profiling==3.1.1) (2021.10.8)
Requirement already satisfied: PyWavelets in /usr/local/lib/python3.7/dist-packages (from imagehash->visions[type_image_path]==0.7.4->pandas-profiling==3.1.1) (1.2.0)
Requirement already satisfied: pandas-profiling in /usr/local/lib/python3.7/dist-packages (3.1.1)
Requirement already satisfied: pydantic>=1.8.1 in /usr/local/lib/python3.7/dist-packages (from pandas-profiling) (1.8.2)
Requirement already satisfied: visions[type_image_path]==0.7.4 in /usr/local/lib/python3.7/dist-packages (from pandas-profiling) (0.7.4)
Requirement already satisfied: jinja2>=2.11.1 in /usr/local/lib/python3.7/dist-packages (from pandas-profiling) (2.11.3)
Requirement already satisfied: joblib~=1.1.0 in /usr/local/lib/python3.7/dist-packages (from pandas-profiling) (1.1.0)
Requirement already satisfied: htmlmin>=0.1.12 in /usr/local/lib/python3.7/dist-packages (from pandas-profiling) (0.1.12)
Requirement already satisfied: missingno>=0.4.2 in /usr/local/lib/python3.7/dist-packages (from pandas-profiling) (0.5.0)
Requirement already satisfied: requests>=2.24.0 in /usr/local/lib/python3.7/dist-packages (from pandas-profiling) (2.26.0)
Requirement already satisfied: phik>=0.11.1 in /usr/local/lib/python3.7/dist-packages (from pandas-profiling) (0.12.0)
Requirement already satisfied: tqdm>=4.48.2 in /usr/local/lib/python3.7/dist-packages (from pandas-profiling) (4.62.3)
Requirement already satisfied: seaborn>=0.10.1 in /usr/local/lib/python3.7/dist-packages (from pandas-profiling) (0.11.2)
Requirement already satisfied: matplotlib>=3.2.0 in /usr/local/lib/python3.7/dist-packages (from pandas-profiling) (3.2.2)
Requirement already satisfied: pandas!=1.0.0,!=1.0.1,!=1.0.2,!=1.1.0,>=0.25.3 in /usr/local/lib/python3.7/dist-packages (from pandas-profiling) (1.1.5)
Requirement already satisfied: PyYAML>=5.0.0 in /usr/local/lib/python3.7/dist-packages (from pandas-profiling) (6.0)
Requirement already satisfied: markupsafe~=2.0.1 in /usr/local/lib/python3.7/dist-packages (from pandas-profiling) (2.0.1)
Requirement already satisfied: scipy>=1.4.1 in /usr/local/lib/python3.7/dist-packages (from pandas-profiling) (1.7.3)
Requirement already satisfied: multimethod>=1.4 in /usr/local/lib/python3.7/dist-packages (from pandas-profiling) (1.6)
Requirement already satisfied: numpy>=1.16.0 in /usr/local/lib/python3.7/dist-packages (from pandas-profiling) (1.19.5)
Requirement already satisfied: tangled-up-in-unicode==0.2.0 in /usr/local/lib/python3.7/dist-packages (from pandas-profiling) (0.2.0)
Requirement already satisfied: attrs>=19.3.0 in /usr/local/lib/python3.7/dist-packages (from visions[type_image_path]==0.7.4->pandas-profiling) (21.2.0)
Requirement already satisfied: networkx>=2.4 in /usr/local/lib/python3.7/dist-packages (from visions[type_image_path]==0.7.4->pandas-profiling) (2.6.3)
Requirement already satisfied: Pillow in /usr/local/lib/python3.7/dist-packages (from visions[type_image_path]==0.7.4->pandas-profiling) (7.1.2)
Requirement already satisfied: imagehash in /usr/local/lib/python3.7/dist-packages (from visions[type_image_path]==0.7.4->pandas-profiling) (4.2.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=3.2.0->pandas-profiling) (1.3.2)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=3.2.0->pandas-profiling) (3.0.6)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=3.2.0->pandas-profiling) (2.8.2)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=3.2.0->pandas-profiling) (0.11.0)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.7/dist-packages (from pandas!=1.0.0,!=1.0.1,!=1.0.2,!=1.1.0,>=0.25.3->pandas-profiling) (2018.9)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.7/dist-packages (from pydantic>=1.8.1->pandas-profiling) (3.10.0.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.1->matplotlib>=3.2.0->pandas-profiling) (1.15.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests>=2.24.0->pandas-profiling) (2021.10.8)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests>=2.24.0->pandas-profiling) (1.24.3)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.7/dist-packages (from requests>=2.24.0->pandas-profiling) (2.0.8)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests>=2.24.0->pandas-profiling) (2.10)
Requirement already satisfied: PyWavelets in /usr/local/lib/python3.7/dist-packages (from imagehash->visions[type_image_path]==0.7.4->pandas-profiling) (1.2.0)

In [ ]:
profile_hospital = ProfileReport(hospital_info, title="Pandas Profiling Report - Hospital_Info", infer_dtypes=False)

NameError: ignored

In [ ]:
profile_outpatient = ProfileReport(outpatient, title="Pandas Profiling Report - Outpatient_Info", infer_dtypes=False)

In [ ]:
profile_inpatient = ProfileReport(inpatient, title="Pandas Profiling Report - Inpatient_Info", infer_dtypes=False)

#Data Cleaning And Transformation

In [ ]:
hopitaldf = hospital.dropna()
hopitaldf.sample(1)

     provider_id  ...                      location
4116      171357  ...  POINT (-97.187589 38.361495)

[1 rows x 29 columns]

In [ ]:
inpatientdf = inpatient.dropna()
inpatientdf.sample(1)

        provider_id  ... average_medicare_payments
174976       100088  ...                   4910.35

[1 rows x 12 columns]

In [ ]:
outpatientdf = outpatient.dropna()
outpatientdf.sample(1)

       provider_id  ... average_total_payments
26968       240141  ...             290.149609

[1 rows x 11 columns]

In [ ]:
### clean the nulls of the columns
hospitaldf1 = hospital[hospital['hospital_overall_rating'].notna()] 
hospitaldf1['hospital_overall_rating'].isna().sum()

0

In [ ]:
hospitaldf2 = hospital[hospital['mortality_national_comparison'].notna()] 
hospitaldf2['mortality_national_comparison'].isna().sum()

0

In [ ]:
### merge cleaned colunms to a new dataframe
hospital_merge = pd.concat([hospitaldf1,hospitaldf2])
hospital_merge.sample(5)

     provider_id  ...                               location
371       110128  ...                                    NaN
2830      420108  ...           POINT (-81.628668 34.711438)
4762      454129  ...  POINT (-97.682259 30.615521000000005)
4853      454119  ...             POINT (-96.86999 33.04477)
781       450135  ...            POINT (-97.339313 32.73848)

[5 rows x 29 columns]

In [ ]:
### cleaning the common colunm 'provider_id' to string
hospital_merge['provider_id'] = hospital['provider_id'].astype(str)
outpatientdf['provider_id'] = outpatient['provider_id'].astype(str)
inpatientdf['provider_id'] = inpatient['provider_id'].astype(str)

In [ ]:
###Get Stony Brook data
hospital_sb = hospital[hospital['city'].str.contains('STONY')]
hospital_sb
##Provider ID for Stony Brook is 330393

     provider_id  ... location
2139      330393  ...      NaN

[1 rows x 29 columns]

In [ ]:
hospital_ny = hospital[hospital['state'].str.contains('NY')]
hospital_ny

     provider_id  ...                              location
4         330080  ...          POINT (-73.924072 40.817681)
11        330125  ...          POINT (-77.584424 43.192542)
12        330221  ...          POINT (-73.917648 40.704699)
20        330231  ...           POINT (-73.803431 40.71698)
22        330009  ...  POINT (-73.903756 40.83175000000001)
...          ...  ...                                   ...
5210      334022  ...          POINT (-78.868415 42.918258)
5227      334064  ...          POINT (-73.382467 40.792705)
5254      334001  ...          POINT (-76.139777 43.045384)
5269      334049  ...          POINT (-73.783423 43.058364)
5282      33025F  ...           POINT (-73.976767 41.40072)

[191 rows x 29 columns]

#Merge Tables for Questions Analysis

In [ ]:
outpatient_hospital = outpatientdf.merge(hospital_merge, how = 'left', left_on='provider_id', right_on='provider_id')
outpatient_hospital

      provider_id  ... location
0           30036  ...      NaN
1           30036  ...      NaN
2           30036  ...      NaN
3           30036  ...      NaN
4           30036  ...      NaN
...           ...  ...      ...
59294       50573  ...      NaN
59295       50573  ...      NaN
59296       50573  ...      NaN
59297       50573  ...      NaN
59298       50573  ...      NaN

[59299 rows x 39 columns]

In [ ]:
#Full Outer Join
outhospital = pd.merge(hospital_merge, outpatientdf, on='provider_id',how='outer')
outhospital

      provider_id  ... average_total_payments
0          310119  ...              42.037500
1          310119  ...             956.672500
2          310119  ...            2254.703333
3          310119  ...            1591.858235
4          310119  ...             212.170397
...           ...  ...                    ...
65186       50573  ...              56.530303
65187       50573  ...             119.803922
65188       50573  ...             112.518926
65189       50573  ...              40.398146
65190       50573  ...             145.338485

[65191 rows x 39 columns]

In [ ]:
inhospital = pd.merge(hospital_merge, inpatientdf, on='provider_id',how='outer')
inhospital

       provider_id  ... average_medicare_payments
0           310119  ...                 153923.69
1           310119  ...                  60775.83
2           310119  ...                  49598.07
3           310119  ...                  21734.51
4           310119  ...                  13112.69
...            ...  ...                       ...
373740       50573  ...                  11455.69
373741       50573  ...                   6197.43
373742       50573  ...                   3876.28
373743       50573  ...                  25490.93
373744       50573  ...                  15590.73

[373745 rows x 40 columns]

Questions for Streamlit
1. How does Stony Brook hospital’s overall rating compare to the rest of NY?
2. What is the most expensive inpatient DRGs for Stony Brook? 
3. What is the most expensive outpatient APCs for Stony Brook? 
4. What is the Stony Brook average outpatient APCs compares to the average outpatient APCs of NY? 
5. What is the Stony Brook average inpatient DRGs compared to the average inpatient DRGs of NY? 
6. What is the Stony Brook national outpatient mortality rate compared to New York outpatient national mortality rate?